### PR TITLE
Add a concrete implementation for sending multiple requests

### PR DESCRIPTION
**Pull request by joelwurtz**
Following removal of sendRequests in https://github.com/php-http/httplug/pull/75

### CODE REVIEW

**Comment by sagikazarmark** [comment]
:+1:

**Comment by sagikazarmark** [comment]
Not an important thing, but you used a different email address in this PR. AFAIK you used the gmail address so far.

**Comment by joelwurtz** [comment]
Both are pretty much alike so no problem :)

**Comment by sagikazarmark** [comment]
Ok

**Comment by joelwurtz** [comment]
I take the initiative to remove interface of BatchResult in this PR, as IMO it is no longer needed

**Comment by sagikazarmark** [comment]
Agreed, like it.

**Pull request merged**
